name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CMGR_LOGGING: debug

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.26.x'
        cache: true
      id: go

    - name: Check out code
      uses: actions/checkout@v6

    - name: Get dependencies
      run: go mod download

    - name: Golang linting
      run: go vet ./...

    - name: Build
      run: |
        mkdir -p bin
        go build -v -ldflags "-X github.com/picoCTF/cmgr/cmgr.version=$(git describe --tags --always)" -o bin/ ./cmd/...

    - name: Unit Tests
      run: go test -v ./...

    - name: Prepare Integration Tests
      run:  mkdir artifacts

    - name: Integration Tests
      run: CMGR_DIR=examples CMGR_ARTIFACT_DIR=artifacts bin/cmgr test --require-solve examples
